title: Karma Bird House
year: 2018
email: hello@karmabird.house
address: 47 Maple St. Burlington, Vermont
description: A place where curiousities collide. Spaces for people, organizations, non-profits, community events and art. Home to Maglianero Cafe and Iskra Print Collective.
baseurl: ""
url: ""
future: true

collections:
  pages:
    output: true
    permalink: /:title/
  directory:
    output: false
  spaces:
    output: true
    permalink: /:collection/:title/   
  happenings:
    output: true
    permalink: /happening/:title/
  slider:
    output: false

markdown: kramdown
theme:
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  
pagination:
  enabled: true
  debug: false
  collection: 'all'
  per_page: 6
  permalink: '/page/:num/'
  title: ':title / :num'
  limit: 0
  sort_field: 'start-date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html