title: The Karma Bird House
year: 2019
email: hello@karmabird.house
address: 47 Maple St. Burlington, Vermont
description: Spaces available for people, start ups, organizations, non-profits, community events, art and music. Home to Maglianero Cafe, Iskra Print Collective, The Karma Bird House Gallery.
image: "/assets/images/karma-social.jpg"
baseurl: ""
url: ""
future: true

collections:
  pages:
    output: true
    permalink: /:title/
  people:
    output: false  
  directory:
    output: false
  spaces:
    output: true
    permalink: /:collection/:title/   
  happenings:
    output: true
    permalink: /happening/:title/
  slider:
    output: false

markdown: kramdown
theme:
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  
pagination:
  enabled: true
  debug: false
  collection: 'all'
  per_page: 6
  permalink: '/page/:num/'
  title: ':title / :num'
  limit: 0
  sort_field: 'start-date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html