backend:
  name: git-gateway
  branch: master

media_library:
 name: uploadcare # File uploader options: https://uploadcare.com/docs/file_uploads/widget/options/
 config:
   publicKey: a9b01c8a17e1d9367673
   multiple: true
   tabs: file gdrive dropbox instagram

display_url: https://karmabird.house

collections:
  - label: "Happenings"
    name: "happenings"
    folder: "_happenings"
    label_singular: "Happening"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "happening"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "select", options: ["Maglianero Cafe", "Iskra Print Collective", "The Karma Bird House Gallery", "Roof Top Space", "The Second Floor"]}
      - {label: "Start", name: "start-date", widget: "date"}
      - {label: "End", name: "end-date", widget: "date", required: false}
      - {label: "Time", name: "time", widget: "string", required: false}
      - {label: "Feature Image", name: "feature-image", widget: "image"}
      - {label: "Vimeo", name: "vimeo", widget: "string", required: false}      
      - {label: "Images", name: "images", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Directory"
    name: "directory"
    folder: "_directory"
    label_singular: "Directory Item"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Space", name: "space", widget: "number"}       
      - {label: "Email", name: "email", widget: "string", required: false}         
      - {label: "Website", name: "website", widget: "string", required: false}      

  - label: "Spaces"
    name: "spaces"
    folder: "_spaces"
    label_singular: "Space"
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "space"}
      - {label: "Title", name: "title", widget: "string"}       
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}   
      - {label: "Feature-image", name: "feature-image", widget: "image"}         
      - {label: "Images", name: "images", widget: "image", required: false}   
      - {label: "Body", name: "body", widget: "markdown"}  

  - label: "Slider"
    name: "slider"
    folder: "_slider"
    label_singular: "Space"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}       
      - {label: "image", name: "image", widget: "image"}             




