backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images/uploads"

collections:
  - name: "happenings" # Used in routes, e.g., /admin/collections/blog
    label: "Happenings" # Used in the UI
    folder: "_happenings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "happening"}
      - {label: "What", name: "what", widget: "string"}
      - {label: "Where", name: "where", widget: "string"}
      - {label: "Published", name: "date", widget: "date"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Starts", name: "start-date", widget: "datetime"}
      - {label: "Ends", name: "end-date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Link Text", name: "link-text", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: 'Spaces'
    label: 'Spaces'
    label_singular: 'Space Type'
    create: true
    widget: list
    files:
      - name: 'spaces'
    collections:
        file: '_data/spaces.yml'
        description: 'Offices'
        fields:
          - name: Offices
            label: Offices
            label_singular: 'Person / Company'
            widget: list
            fields: