backend:
  name: git-gateway
  repo: alder-studio/karma-bird-house # Path to your GitHub repository
  branch: staging

media_folder: "/assets/images/uploads"
display_url: https://karmabird.house
logo_url: /assets/images/logo/black.svg
collections:


  - name: "happenings" # Used in routes, e.g., /admin/collections/blog
    label: "Happenings" # Used in the UI
    description: Public events for birdhouse and beyond. # Used in the UI
    label_singular: 'Happening'
    folder: "_happenings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: 'Directory'
    label: 'Directory'
    create: false # Allow users to create new documents in this collection
    widget: list
    files:
      - name: 'directory'
        label: 'Directory'
        file: '_data/directory.yml'
        description: 'Directory'
        fields:
          - name: offices
            label: Offices
            label_singular: 'Person / Company'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string', hint: 'First and Last' }
              - { label: 'Website', name: 'website', widget: 'string', hint: 'First and Last' }
              - { label: 'Email', name: 'email', widget: 'string', hint: 'First and Last' }
              - { label: 'Office', name: 'office', widget: 'string' }