backend:
  name: git-gateway
  branch: master

media_folder: "assets/images"
display_url: https://karmabird.house

collections:
  - name: "happenings" # Used in routes, e.g., /admin/collections/blog
    label: "Happenings" # Used in the UI
    folder: "_happenings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "happening"}
      - {label: "What", name: "what", widget: "string"}
      - {label: "Where", name: "where", widget: "string"}
      - {label: "Published", name: "date", widget: "date"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Starts", name: "start-date", widget: "datetime"}
      - {label: "Ends", name: "end-date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Link Text", name: "link-text", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Spaces"
    name: "spaces"
    editor:
      preview: false
    files:
      - label: "Work Space"
        name: "work-space"
        file: "_data/spaces.yml"
        fields:
          - label: Work Space
            name: workspace
            widget: list
            fields:
              - {label: Office, name: office, widget: string}
              - {label: Email, name: email, widget: string}
              - {label: Name, name: name, widget: string}          
              - {label: Website, name: website, widget: string}           
          - label: Event Space
            name: event-space
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Capacity, name: capacity, widget: number}       
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: image}                             