backend:
  name: git-gateway
  branch: master

media_library:
 name: uploadcare # File uploader options: https://uploadcare.com/docs/file_uploads/widget/options/
 config:
   publicKey: a9b01c8a17e1d9367673
   multiple: true
   tabs: file gdrive dropbox instagram

display_url: https://karmabird.house

collections:
  - label: "Happenings"
    name: "happenings"
    folder: "_happenings"
    label_singular: "Happening"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "happening"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "select", options: ["Maglianero Cafe", "Roof Space"]}
      - {label: "Start", name: "start-date", widget: "datetime"}
      - {label: "End", name: "end-date", widget: "datetime", required: false}
      - {label: "Feature Image", name: "feature-image", widget: "image"}
      - {label: "Images", name: "images", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

collections:
  - label: "Directory"
    name: "directory"
    folder: "_directory"
    label_singular: "Office"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Office", name: "office", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}          
      - {label: "Website", name: "website", widget: "string"}          